/*
Package test is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/nleiva/go/pkg/mod/github.com/openconfig/ygot@v0.31.0/genutil/names.go
using the following YANG input files:
	- base.yang
Imported modules were sourced from:
	- ...
*/
package test

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

// UnionInt8 is an int8 type assignable to unions of which it is a subtype.
type UnionInt8 int8

// UnionInt16 is an int16 type assignable to unions of which it is a subtype.
type UnionInt16 int16

// UnionInt32 is an int32 type assignable to unions of which it is a subtype.
type UnionInt32 int32

// UnionInt64 is an int64 type assignable to unions of which it is a subtype.
type UnionInt64 int64

// UnionUint8 is a uint8 type assignable to unions of which it is a subtype.
type UnionUint8 uint8

// UnionUint16 is a uint16 type assignable to unions of which it is a subtype.
type UnionUint16 uint16

// UnionUint32 is a uint32 type assignable to unions of which it is a subtype.
type UnionUint32 uint32

// UnionUint64 is a uint64 type assignable to unions of which it is a subtype.
type UnionUint64 uint64

// UnionFloat64 is a float64 type assignable to unions of which it is a subtype.
type UnionFloat64 float64

// UnionString is a string type assignable to unions of which it is a subtype.
type UnionString string

// UnionBool is a bool type assignable to unions of which it is a subtype.
type UnionBool bool

// UnionUnsupported is an interface{} wrapper type for unsupported types. It is
// assignable to unions of which it is a subtype.
type UnionUnsupported struct {
	Value interface{}
}

var (
	SchemaTree map[string]*yang.Entry
	ΛEnumTypes map[string][]reflect.Type
)

func init() {
	var err error
	initΛEnumTypes()
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Test{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Base_BaseContainer represents the /base/base-container YANG schema element.
type Base_BaseContainer struct {
	BaseContainerLeaf_1	*string	`path:"base-container-leaf-1" module:"base"`
	BaseContainerLeaf_2	*int32	`path:"base-container-leaf-2" module:"base"`
	BaseContainerLeaf_3	*int32	`path:"base-container-leaf-3" module:"base"`
	BaseContainerList_1	map[Base_BaseContainer_BaseContainerList_1_Name_Union]*Base_BaseContainer_BaseContainerList_1	`path:"base-container-list-1" module:"base"`
}

// IsYANGGoStruct ensures that Base_BaseContainer implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Base_BaseContainer) IsYANGGoStruct() {}

// NewBaseContainerList_1 creates a new entry in the BaseContainerList_1 list of the
// Base_BaseContainer struct. The keys of the list are populated from the input
// arguments.
func (t *Base_BaseContainer) NewBaseContainerList_1(Name Base_BaseContainer_BaseContainerList_1_Name_Union) (*Base_BaseContainer_BaseContainerList_1, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.BaseContainerList_1 == nil {
		t.BaseContainerList_1 = make(map[Base_BaseContainer_BaseContainerList_1_Name_Union]*Base_BaseContainer_BaseContainerList_1)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.BaseContainerList_1[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list BaseContainerList_1", key)
	}

	t.BaseContainerList_1[key] = &Base_BaseContainer_BaseContainerList_1{
		Name: Name,
	}

	return t.BaseContainerList_1[key], nil
}

// GetOrCreateBaseContainerList_1Map returns the list (map) from Base_BaseContainer.
//
// It initializes the field if not already initialized.
func (t *Base_BaseContainer) GetOrCreateBaseContainerList_1Map() map[Base_BaseContainer_BaseContainerList_1_Name_Union]*Base_BaseContainer_BaseContainerList_1 {
	if t.BaseContainerList_1 == nil {
		t.BaseContainerList_1 = make(map[Base_BaseContainer_BaseContainerList_1_Name_Union]*Base_BaseContainer_BaseContainerList_1)
	}
	return t.BaseContainerList_1
}

// GetOrCreateBaseContainerList_1 retrieves the value with the specified keys from
// the receiver Base_BaseContainer. If the entry does not exist, then it is created.
// It returns the existing or new list member.
func (t *Base_BaseContainer) GetOrCreateBaseContainerList_1(Name Base_BaseContainer_BaseContainerList_1_Name_Union) (*Base_BaseContainer_BaseContainerList_1){

	key := Name

	if v, ok := t.BaseContainerList_1[key]; ok {
		return v
	}
	// Panic if we receive an error, since we should have retrieved an existing
	// list member. This allows chaining of GetOrCreate methods.
	v, err := t.NewBaseContainerList_1(Name)
	if err != nil {
		panic(fmt.Sprintf("GetOrCreateBaseContainerList_1 got unexpected error: %v", err))
	}
	return v
}

// GetBaseContainerList_1 retrieves the value with the specified key from
// the BaseContainerList_1 map field of Base_BaseContainer. If the receiver is nil, or
// the specified key is not present in the list, nil is returned such that Get*
// methods may be safely chained.
func (t *Base_BaseContainer) GetBaseContainerList_1(Name Base_BaseContainer_BaseContainerList_1_Name_Union) (*Base_BaseContainer_BaseContainerList_1){

	if t == nil {
		return nil
	}

  key := Name

  if lm, ok := t.BaseContainerList_1[key]; ok {
    return lm
  }
  return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Base_BaseContainer) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Base_BaseContainer"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Base_BaseContainer) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Base_BaseContainer) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Base_BaseContainer.
func (*Base_BaseContainer) ΛBelongingModule() string {
	return "base"
}


// Base_BaseContainer_BaseContainerList_1 represents the /base/base-container/base-container-list-1 YANG schema element.
type Base_BaseContainer_BaseContainerList_1 struct {
	Name	Base_BaseContainer_BaseContainerList_1_Name_Union	`path:"name" module:"base"`
}

// IsYANGGoStruct ensures that Base_BaseContainer_BaseContainerList_1 implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Base_BaseContainer_BaseContainerList_1) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Base_BaseContainer_BaseContainerList_1 struct, which is a YANG list entry.
func (t *Base_BaseContainer_BaseContainerList_1) ΛListKeyMap() (map[string]interface{}, error) {

	return map[string]interface{}{
		"name": t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Base_BaseContainer_BaseContainerList_1) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Base_BaseContainer_BaseContainerList_1"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Base_BaseContainer_BaseContainerList_1) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Base_BaseContainer_BaseContainerList_1) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Base_BaseContainer_BaseContainerList_1.
func (*Base_BaseContainer_BaseContainerList_1) ΛBelongingModule() string {
	return "base"
}

// Base_BaseContainer_BaseContainerList_1_Name_Union is an interface that is implemented by valid types for the union
// for the leaf /base/base-container/base-container-list-1/name within the YANG schema.
// Union type can be one of [UnionString, UnionUint32].
type Base_BaseContainer_BaseContainerList_1_Name_Union interface {
	// Union type can be one of [UnionString, UnionUint32]
	Documentation_for_Base_BaseContainer_BaseContainerList_1_Name_Union()
}

// Documentation_for_Base_BaseContainer_BaseContainerList_1_Name_Union ensures that UnionString
// implements the Base_BaseContainer_BaseContainerList_1_Name_Union interface.
func (UnionString) Documentation_for_Base_BaseContainer_BaseContainerList_1_Name_Union() {}

// Documentation_for_Base_BaseContainer_BaseContainerList_1_Name_Union ensures that UnionUint32
// implements the Base_BaseContainer_BaseContainerList_1_Name_Union interface.
func (UnionUint32) Documentation_for_Base_BaseContainer_BaseContainerList_1_Name_Union() {}

// To_Base_BaseContainer_BaseContainerList_1_Name_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Base_BaseContainer_BaseContainerList_1_Name_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Base_BaseContainer_BaseContainerList_1) To_Base_BaseContainer_BaseContainerList_1_Name_Union(i interface{}) (Base_BaseContainer_BaseContainerList_1_Name_Union, error) {
	if v, ok := i.(Base_BaseContainer_BaseContainerList_1_Name_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint32:
		return UnionUint32(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Base_BaseContainer_BaseContainerList_1_Name_Union, unknown union type, got: %T, want any of [string, uint32]", i, i)
}


// Test represents the /test YANG schema element.
type Test struct {
	BaseContainer	*Base_BaseContainer	`path:"base-container" module:"base"`
}

// IsYANGGoStruct ensures that Test implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Test) IsYANGGoStruct() {}

// GetOrCreateBaseContainer retrieves the value of the BaseContainer field
// or returns the existing field if it already exists.
func (t *Test) GetOrCreateBaseContainer() *Base_BaseContainer {
	if t.BaseContainer != nil {
		return t.BaseContainer
	}
	t.BaseContainer = &Base_BaseContainer{}
	return t.BaseContainer
}

// GetBaseContainer returns the value of the BaseContainer struct pointer
// from Test. If the receiver or the field BaseContainer is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Test) GetBaseContainer() *Base_BaseContainer {
	if t != nil && t.BaseContainer != nil {
		return t.BaseContainer
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Test) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Test"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Test) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Test) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Test.
func (*Test) ΛBelongingModule() string {
	return ""
}



var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x5d, 0x4f, 0xdb, 0x30,
		0x14, 0x7d, 0xcf, 0xaf, 0x88, 0xac, 0x3d, 0xa1, 0x14, 0xf2, 0x05, 0x29, 0x7d, 0xe3, 0x63, 0x68,
		0x12, 0x63, 0x43, 0x8c, 0xed, 0x85, 0x21, 0xe4, 0x05, 0x37, 0x58, 0x4b, 0x1d, 0x64, 0x3b, 0x1b,
		0xd5, 0x96, 0xff, 0x3e, 0x39, 0x49, 0x03, 0x69, 0xe2, 0xc4, 0x31, 0x94, 0xad, 0x5a, 0x5f, 0xa0,
		0x8d, 0xcf, 0xb5, 0xef, 0xbd, 0xe7, 0xc4, 0x3e, 0x4d, 0x7e, 0x19, 0xa6, 0x69, 0x9a, 0xe0, 0x03,
		0x9c, 0x21, 0x30, 0x31, 0x01, 0x47, 0x8c, 0x03, 0xab, 0xb8, 0x76, 0x8a, 0xc9, 0x2d, 0x98, 0x98,
		0x4e, 0xf9, 0xf5, 0x28, 0x21, 0x53, 0x1c, 0x81, 0x89, 0x69, 0x97, 0x17, 0x8e, 0x31, 0x05, 0x13,
		0xb3, 0x98, 0x20, 0xbf, 0xf0, 0x0d, 0x32, 0x34, 0x0a, 0x13, 0xc2, 0x21, 0x26, 0xa8, 0x3e, 0x56,
		0x5b, 0x64, 0x09, 0x67, 0xd5, 0x51, 0xf5, 0x65, 0xab, 0xcb, 0xcb, 0xcb, 0x57, 0x03, 0xe7, 0x14,
		0x4d, 0xf1, 0x43, 0x63, 0xb5, 0xda, 0x8a, 0xb3, 0xf9, 0x7d, 0x81, 0xb2, 0x9a, 0x98, 0x4f, 0x49,
		0x4a, 0x43, 0xd4, 0x1a, 0x5f, 0xe4, 0x83, 0xe6, 0x3f, 0x13, 0x2a, 0x52, 0x02, 0xd2, 0x49, 0x72,
		0xe0, 0x3b, 0xc8, 0x0e, 0x68, 0x94, 0xce, 0x10, 0xe1, 0x60, 0x62, 0x72, 0x9a, 0x22, 0x09, 0xf0,
		0x09, 0xea, 0x31, 0xb3, 0x06, 0x34, 0xab, 0x5d, 0xc9, 0x96, 0xaa, 0x5e, 0x6e, 0xbe, 0x84, 0x84,
		0x51, 0x8c, 0xe0, 0x74, 0xe4, 0xc8, 0xab, 0x6b, 0xe7, 0x64, 0x11, 0x26, 0x29, 0xa0, 0xa4, 0xc8,
		0x96, 0x0c, 0xcb, 0xa8, 0x52, 0xa1, 0x6c, 0x08, 0x75, 0xaa, 0x14, 0x0e, 0xa6, 0x72, 0x30, 0xa5,
		0x03, 0xa9, 0x6d, 0xa7, 0x58, 0x42, 0x75, 0x35, 0xf7, 0xe5, 0xfc, 0x1e, 0xa9, 0xf5, 0x8c, 0x71,
		0x8a, 0x49, 0xd4, 0xd5, 0xb1, 0xc5, 0x4d, 0x36, 0x36, 0xd4, 0xf2, 0x6a, 0xc9, 0xa9, 0x55, 0x32,
		0xae, 0x9e, 0xd2, 0xdc, 0x8d, 0xd2, 0xd6, 0x53, 0x69, 0x39, 0x99, 0x5c, 0xc0, 0xfb, 0xc5, 0xe6,
		0x75, 0x40, 0x2e, 0x20, 0x89, 0xc4, 0x84, 0x57, 0x9d, 0x45, 0x77, 0x37, 0x3d, 0x9f, 0xe8, 0x0c,
		0x93, 0x5e, 0x76, 0x2a, 0xf0, 0x17, 0x18, 0xa7, 0x62, 0x55, 0xd7, 0xf1, 0x03, 0x7f, 0xec, 0xed,
		0xf9, 0x63, 0x4b, 0x2d, 0xf0, 0x84, 0xc2, 0x90, 0xe3, 0x84, 0x1c, 0xe3, 0x08, 0x73, 0x26, 0xd7,
		0x5f, 0xb3, 0x6f, 0x28, 0x82, 0x1c, 0xff, 0x40, 0x25, 0xc7, 0xbd, 0x41, 0x99, 0xa5, 0x50, 0x32,
		0x7c, 0x78, 0x46, 0xc9, 0xc1, 0x2b, 0x96, 0x3c, 0x85, 0x31, 0x53, 0xa8, 0xd9, 0xd0, 0x1b, 0xbd,
		0x7e, 0xe1, 0xbd, 0xcc, 0xd3, 0xdb, 0xcb, 0xbc, 0xcd, 0x5e, 0xb6, 0x9e, 0x7b, 0xd9, 0x6c, 0x3e,
		0xca, 0xf9, 0xc4, 0x84, 0x7b, 0xee, 0xfa, 0x6f, 0x6a, 0xce, 0xbf, 0x77, 0x63, 0xaf, 0x6a, 0x33,
		0xf3, 0xd7, 0x6d, 0x0f, 0xb3, 0xfe, 0x8e, 0x22, 0xec, 0xff, 0x47, 0x12, 0xae, 0xbd, 0x39, 0xd7,
		0x5a, 0xce, 0x35, 0xcc, 0xb8, 0xce, 0xaf, 0xc1, 0x22, 0xac, 0xfb, 0x5c, 0x73, 0x36, 0xe7, 0xda,
		0x6b, 0x9e, 0x6b, 0xb2, 0x07, 0x00, 0x15, 0x80, 0x14, 0x2d, 0xeb, 0x69, 0xc2, 0xa2, 0xb1, 0x39,
		0xba, 0xa7, 0x9c, 0x6e, 0x03, 0xa3, 0x4c, 0xf8, 0x10, 0xe2, 0x75, 0x04, 0x30, 0x54, 0x08, 0xda,
		0x82, 0xd0, 0x16, 0x86, 0xa6, 0x40, 0x5e, 0xe4, 0x70, 0xe9, 0x37, 0x44, 0x8d, 0x9e, 0xa7, 0x04,
		0x27, 0x44, 0xa5, 0xe1, 0x8b, 0x9d, 0x60, 0x5f, 0x01, 0x5b, 0xa6, 0x71, 0xa5, 0xd4, 0x28, 0x35,
		0x02, 0x87, 0x3d, 0x03, 0x91, 0x3f, 0x13, 0x19, 0x10, 0x73, 0x0e, 0x39, 0x47, 0x94, 0x28, 0x17,
		0x52, 0x05, 0x7e, 0x4d, 0x6d, 0xdb, 0x0b, 0xb7, 0xb7, 0xf2, 0xff, 0xe8, 0xf7, 0x9b, 0xed, 0x2d,
		0xa0, 0x3c, 0xc1, 0xb5, 0x12, 0x32, 0xb3, 0x56, 0xd5, 0xda, 0x34, 0x77, 0xc8, 0x1a, 0xad, 0x0d,
		0x06, 0x84, 0xa8, 0x99, 0x67, 0xfd, 0x6a, 0xb4, 0xac, 0x94, 0xd4, 0x6e, 0xd8, 0x96, 0x5e, 0xbc,
		0xae, 0xfb, 0x78, 0xbe, 0x1b, 0xd1, 0x94, 0x8b, 0xb6, 0x33, 0xeb, 0x70, 0xa5, 0x81, 0x17, 0xf8,
		0xce, 0xd8, 0xf5, 0xd6, 0xbf, 0x87, 0xc6, 0x6a, 0xd0, 0x8a, 0x37, 0xbc, 0xf1, 0xbc, 0x79, 0xb2,
		0x17, 0x72, 0x26, 0xa7, 0x68, 0xde, 0xe3, 0x28, 0xc0, 0x7b, 0xcc, 0xf8, 0x01, 0xe7, 0x3d, 0x0e,
		0xe6, 0x0c, 0x93, 0xb7, 0x31, 0x12, 0xe7, 0x63, 0x0f, 0xab, 0x42, 0x88, 0x4f, 0x90, 0xce, 0xd8,
		0xf7, 0xf7, 0x02, 0xdf, 0x17, 0xc2, 0xb2, 0xf7, 0x77, 0x77, 0x9d, 0x3d, 0x67, 0xb7, 0x23, 0xf8,
		0x23, 0xbd, 0x45, 0x14, 0xdd, 0x1e, 0x8a, 0xac, 0x49, 0x1a, 0xc7, 0x2a, 0xd0, 0xcf, 0x2c, 0x7f,
		0xc1, 0x25, 0x97, 0x89, 0xac, 0x39, 0x07, 0x84, 0x24, 0x1c, 0x0a, 0xb9, 0x76, 0xd7, 0xce, 0xc2,
		0x3b, 0x34, 0x83, 0xf7, 0x90, 0xdf, 0x89, 0x5e, 0xee, 0x08, 0x43, 0xbe, 0x53, 0x77, 0xe5, 0x3b,
		0x43, 0x4c, 0x7a, 0x31, 0x27, 0xa7, 0x69, 0xc8, 0x4b, 0x5f, 0x08, 0x0e, 0x21, 0x43, 0x37, 0xe2,
		0xcf, 0xd1, 0x62, 0x8a, 0xfa, 0x37, 0xc1, 0xd1, 0x8d, 0x03, 0x54, 0x7f, 0x7c, 0x74, 0xbe, 0xad,
		0xea, 0xa9, 0x5a, 0xa1, 0xda, 0xb6, 0x37, 0x77, 0x7d, 0xf5, 0xd4, 0x73, 0x7f, 0xcc, 0xb0, 0xf8,
		0x54, 0xe6, 0x28, 0xcb, 0x0d, 0x60, 0x76, 0x02, 0xbf, 0xa3, 0x8b, 0x24, 0x69, 0x7a, 0xba, 0xe5,
		0x7c, 0xc1, 0xd3, 0xa1, 0x5a, 0x52, 0x97, 0x88, 0xf1, 0x22, 0x8d, 0xcc, 0xc8, 0xfe, 0x00, 0x00,
		0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x0c, 0x1d, 0x99, 0x6c, 0x1d, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
func initΛEnumTypes(){
  ΛEnumTypes = map[string][]reflect.Type{
  }
}

